# Generated by Django 2.2.3 on 2019-08-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Coordenadas',
        ),
    ]
