# Generated by Django 2.2.4 on 2019-09-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_onibus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onibus',
        ),
    ]
