# Generated by Django 2.2.3 on 2019-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_onibus'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
