# Generated by Django 2.2.3 on 2019-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_coordenadas_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='velocidade',
            field=models.DecimalField(decimal_places=17, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
