# Generated by Django 2.0.4 on 2019-12-03 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_coordenadas_velocidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('oni_codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('oni_nome', models.CharField(max_length=50)),
                ('oni_mot_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_onibus',
            },
        ),
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('par_codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('par_nome', models.CharField(max_length=50)),
                ('par_x', models.DecimalField(decimal_places=17, max_digits=20)),
                ('par_y', models.DecimalField(decimal_places=17, max_digits=20)),
                ('par_oni_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Onibus')),
            ],
            options={
                'db_table': 'tb_paradas',
            },
        ),
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('rot_codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rot_x', models.DecimalField(decimal_places=17, max_digits=20)),
                ('rot_y', models.DecimalField(decimal_places=17, max_digits=20)),
                ('rot_oni_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Onibus')),
            ],
            options={
                'db_table': 'tb_rotas',
            },
        ),
        migrations.RenameField(
            model_name='coordenadas',
            old_name='velocidade',
            new_name='cor_velocidade',
        ),
        migrations.RenameField(
            model_name='coordenadas',
            old_name='x',
            new_name='cor_x',
        ),
        migrations.RenameField(
            model_name='coordenadas',
            old_name='y',
            new_name='cor_y',
        ),
        migrations.RemoveField(
            model_name='coordenadas',
            name='codigo',
        ),
        migrations.AlterModelTable(
            name='coordenadas',
            table='tb_coordenadas',
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='cor_oni_codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Onibus'),
            preserve_default=False,
        ),
    ]
