# Generated by Django 2.2.7 on 2019-12-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradas',
            name='par_distancia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DistanciasR',
            fields=[
                ('dis_codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dis_distancia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dis_oni_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Onibus')),
            ],
            options={
                'db_table': 'tb_distanciasr',
            },
        ),
    ]
