# Generated by Django 2.2.3 on 2019-12-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191228_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanciaTR',
            fields=[
                ('dtr_codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dtr_distancia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dtr_oni_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Onibus')),
            ],
            options={
                'db_table': 'tb_distanciatr',
            },
        ),
    ]
